### ISSUE TITLE
Newly-added URL-escaping of ESSID in *.conf filenames is not backward-compatible with files saved before this change.

### ISSUE THREAD

**Issue by senquack** [gcwnow/gcwconnect#4]
This bug is resulting from changes made in https://github.com/gcwnow/gcwconnect/commit/c872c89edaf6bc720c52f635f922926641e9a328

**Detailed bug description:** The presence of AP configuration files saved with previous versions of gcwconnect that did not URL-escape filenames can cause gcwconnect to crash. This occurs when their ESSID contained characters that were previously backslash-escaped but are now either URL-escaped (special chars) or not escaped at all (a dash, for instance). Gcwconnect will parse and list the APs in these files, but any attempts to connect through them or delete them from the list will result in a crash.

**Example:**
An AP named HOME-1234 would previously have been saved to 'HOME\-1234.conf', whereas now it would be saved to or loaded from 'HOME-1234.conf'. If you attempt to connect to HOME-1234 with this older file present, it crashes and this error results:
Traceback (most recent call last):
  File "./gcwconnect.py", line 1591, in <module>
    shutil.copy2(netconfdir + quote_plus(ssid) + ".conf", sysconfdir+"config-"+wlan+".conf")
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
IOError: [Errno 2] No such file or directory: '/usr/local/home/.local/share/gcwconnect/networks/HOME-0942.conf'

**Proposed solution:**
Save AP configurations in a different subfolder than 'networks/' in /usr/local/home/.local/share/gcwconnect/ , perhaps 'saved_aps/'. If gcwconnect detects the presence of the old networks/ subfolder, it's obviously from an older firmware and should move each of its configuration files to the new folder, renaming them with the new URL-escaping method based on the ESSID value inside each. The old networks/ subfolder can then be removed.

**Comment by Nebuleon** [comment]
~~Does Nebuleon/gcwconnect@19a6689f08e4483a09fbeeb68ef3c6fe12200774 adequately fix this?~~

Does Nebuleon/gcwconnect@ba9901cc65faff7a43a1c9e5f640d486a62c89f8 adequately fix this?

**Comment by senquack** [comment]
https://github.com/Nebuleon/gcwconnect/commit/ba9901cc65faff7a43a1c9e5f640d486a62c89f8 fixed the issue quite nicely, and cleaner than my proposed solution. Thanks!

**Comment by Nebuleon** [comment]
Imported as gcwnow/gcwconnect@cddc6c905d5beed78a9a37f167d9fddb6538e357. Thanks for your bug report and testing :)
